app:
  await_time: 10
  backoff_start_sleep_time: 0.05
  backoff_factor: 2
  backoff_border_sleep_time: 10
  storage_file_path: misc/stats.json
  log_file_path: logs/debug.log
  log_maxBytes: 1000000
  log_backupCount: 5

postgres:
  DB_NAME: movies_database
  POSTGRES_USER: app
  POSTGRES_PASSWORD: 123qwe
  DB_HOST: postgres
  DB_PORT: 5432
  options: -c search_path=content

elasticsearch:
  discovery.type: single-node
  ES_URL: elasticsearch
  ES_PORT: 9200
  movies_index: movies
  genre_index: genres
  person_index: persons
  bulk_factor: 50
  default_scheme_file: settings/default_scheme_es.json
  genres_scheme_file: settings/genre_scheme_es.json
  persons_scheme_file: settings/person_scheme_es.json
