app:
  await_time: 10
  backoff_start_sleep_time: 0.05
  backoff_factor: 2
  backoff_border_sleep_time: 10
  storage_file_path: settings/storage.json
  log_path: logs/debug.log

postgres:
  DB_NAME: movies_database
  POSTGRES_USER: app
  POSTGRES_PASSWORD: 123qwe
  DB_HOST: localhost
  DB_PORT: 5432
  options: -c search_path=content
  bulk_factor : 100
  limit_query: 1000

elasticsearch:
  discovery.type: single-node
  ES_URL: localhost
  ES_PORT: 9200
  movie_idx: movies
  genre_idx: genres
  person_idx: persons
  bulk_factor: 50
  movies_schema: settings/movies.json
  genres_schema: settings/genres.json
  persons_schema: settings/persons.json
